import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  const handleClick = (URL: string) => {
    router.push(`/${URL}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className={styles.header}>
          <ul>
            <li>
              <h1>Next JS 13 with Turbopack</h1>
            </li>
            <li onClick={() => handleClick("dashboard")}>Dashboard</li>
            <li onClick={() => handleClick("about")}>About</li>
            <li onClick={() => handleClick("categories")}>Categories</li>
          </ul>
        </header>
        <section>
          <div className={styles.section}>
            <div>
              <div>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime,
                accusantium placeat, quo ratione delectus amet modi itaque
                dolorum optio officiis nobis facilis iure aliquam eum autem
                quia! Perferendis, eveniet nam.
              </div>
            </div>

            <div>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime,
              accusantium placeat, quo ratione delectus amet modi itaque dolorum
              optio officiis nobis facilis iure aliquam eum autem quia!
              Perferendis, eveniet nam.
            </div>
            <div>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime,
              accusantium placeat, quo ratione delectus amet modi itaque dolorum
              optio officiis nobis facilis iure aliquam eum autem quia!
              Perferendis, eveniet nam.
            </div>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
